@startuml
User -> "apsi-backend": Authentication Request
"apsi-backend" -> "Mock SSO": Create new session (and provide webhook url)
"apsi-backend" --> User: Respond with URL to mock SSO

User -> "Mock SSO": Authentication Request
"Mock SSO" -> "apsi-backend": Confirms user authority by giving an access token
"Mock SSO" -> User: Confirms user authority by giving an access token

User -> "apsi-backend": Authentication Request with access token
"apsi-backend" --> User: Register account based on data from SSO or find already existing one and return JWT token
@enduml